This notebook loads the OULAD CSV files, inspects their structure, identifies key columns, and prepares the first base dataset for the Potential Pathway Index project.

The goal of this notebook is not to build a model yet.  
The goal is to understand the raw data before making any transformation.

In [3]:
from pathlib import Path

import pandas as pd
import numpy as np

In [4]:
PROJECT_ROOT = Path("..")

DATA_RAW = PROJECT_ROOT / "data" / "raw"
DATA_PROCESSED = PROJECT_ROOT / "data" / "processed"

DATA_PROCESSED.mkdir(parents=True, exist_ok=True)

print("Project root:", PROJECT_ROOT.resolve())
print("Raw data path:", DATA_RAW.resolve())
print("Processed data path:", DATA_PROCESSED.resolve())

Project root: /workspaces/potential-pathway-index
Raw data path: /workspaces/potential-pathway-index/data/raw
Processed data path: /workspaces/potential-pathway-index/data/processed

In [5]:
expected_files = {
    "assessments": "assessments.csv",
    "courses": "courses.csv",
    "student_assessment": "studentAssessment.csv",
    "student_info": "studentInfo.csv",
    "student_registration": "studentRegistration.csv",
    "student_vle": "studentVle.csv",
    "vle": "vle.csv"
}

for table_name, file_name in expected_files.items():
    file_path = DATA_RAW / file_name
    print(f"{table_name:25} | exists: {file_path.exists()} | file: {file_name}")

assessments               | exists: True | file: assessments.csv
courses                   | exists: True | file: courses.csv
student_assessment        | exists: True | file: studentAssessment.csv
student_info              | exists: True | file: studentInfo.csv
student_registration      | exists: True | file: studentRegistration.csv
student_vle               | exists: True | file: studentVle.csv
vle                       | exists: True | file: vle.csv

In [6]:
dataframes = {}

for table_name, file_name in expected_files.items():
    file_path = DATA_RAW / file_name
    
    if file_path.exists():
        dataframes[table_name] = pd.read_csv(file_path)
        print(f"{table_name:25} | loaded successfully | shape: {dataframes[table_name].shape}")
    else:
        print(f"{table_name:25} | file not found | expected file: {file_name}")

assessments               | loaded successfully | shape: (206, 6)
courses                   | loaded successfully | shape: (22, 3)
student_assessment        | loaded successfully | shape: (173912, 5)
student_info              | loaded successfully | shape: (32593, 12)
student_registration      | loaded successfully | shape: (32593, 5)
student_vle               | loaded successfully | shape: (10655280, 6)
vle                       | loaded successfully | shape: (6364, 6)

In [7]:
assessments = dataframes["assessments"]
courses = dataframes["courses"]
student_assessment = dataframes["student_assessment"]
student_info = dataframes["student_info"]
student_registration = dataframes["student_registration"]
student_vle = dataframes["student_vle"]
vle = dataframes["vle"]

print("All tables were assigned successfully.")

All tables were assigned successfully.

In [8]:
def inspect_table(df, table_name):
    """
    Inspect the basic structure of a DataFrame.

    This function shows:
    - number of rows and columns
    - column names
    - data types
    - missing values
    - first rows
    """
    
    print("=" * 80)
    print(f"TABLE: {table_name}")
    print("=" * 80)
    
    print("\nShape:")
    print(df.shape)
    
    print("\nColumns:")
    print(df.columns.tolist())
    
    print("\nData types:")
    print(df.dtypes)
    
    print("\nMissing values:")
    missing_values = df.isnull().sum()
    print(missing_values[missing_values > 0].sort_values(ascending=False))
    
    print("\nFirst rows:")
    display(df.head())

In [9]:
inspect_table(assessments, "assessments")
inspect_table(courses, "courses")
inspect_table(student_assessment, "studentAssessment")
inspect_table(student_info, "studentInfo")
inspect_table(student_registration, "studentRegistration")
inspect_table(student_vle, "studentVle")
inspect_table(vle, "vle")

================================================================================
TABLE: assessments
================================================================================

Shape:
(206, 6)

Columns:
['code_module', 'code_presentation', 'id_assessment', 'assessment_type', 'date', 'weight']

Data types:
code_module              str
code_presentation        str
id_assessment          int64
assessment_type          str
date                 float64
weight               float64
dtype: object

Missing values:
date    11
dtype: int64

First rows:

  code_module code_presentation  id_assessment assessment_type   date  weight
0         AAA             2013J           1752             TMA   19.0    10.0
1         AAA             2013J           1753             TMA   54.0    20.0
2         AAA             2013J           1754             TMA  117.0    20.0
3         AAA             2013J           1755             TMA  166.0    20.0
4         AAA             2013J           1756             TMA  215.0    30.0

================================================================================
TABLE: courses
================================================================================

Shape:
(22, 3)

Columns:
['code_module', 'code_presentation', 'module_presentation_length']

Data types:
code_module                     str
code_presentation               str
module_presentation_length    int64
dtype: object

Missing values:
Series([], dtype: int64)

First rows:

  code_module code_presentation  module_presentation_length
0         AAA             2013J                         268
1         AAA             2014J                         269
2         BBB             2013J                         268
3         BBB             2014J                         262
4         BBB             2013B                         240

================================================================================
TABLE: studentAssessment
================================================================================

Shape:
(173912, 5)

Columns:
['id_assessment', 'id_student', 'date_submitted', 'is_banked', 'score']

Data types:
id_assessment       int64
id_student          int64
date_submitted      int64
is_banked           int64
score             float64
dtype: object

Missing values:
score    173
dtype: int64

First rows:

   id_assessment  id_student  date_submitted  is_banked  score
0           1752       11391              18          0   78.0
1           1752       28400              22          0   70.0
2           1752       31604              17          0   72.0
3           1752       32885              26          0   69.0
4           1752       38053              19          0   79.0

================================================================================
TABLE: studentInfo
================================================================================

Shape:
(32593, 12)

Columns:
['code_module', 'code_presentation', 'id_student', 'gender', 'region', 'highest_education', 'imd_band', 'age_band', 'num_of_prev_attempts', 'studied_credits', 'disability', 'final_result']

Data types:
code_module               str
code_presentation         str
id_student              int64
gender                    str
region                    str
highest_education         str
imd_band                  str
age_band                  str
num_of_prev_attempts    int64
studied_credits         int64
disability                str
final_result              str
dtype: object

Missing values:
imd_band    1111
dtype: int64

First rows:

,code_module,code_presentation,id_student,gender,region,highest_education,imd_band,age_band,num_of_prev_attempts,studied_credits,disability,final_result
0,AAA,2013J,11391,M,East Anglian Region,HE Qualification,90-100%,55<=,0,240,N,Pass
1,AAA,2013J,28400,F,Scotland,HE Qualification,20-30%,35-55,0,60,N,Pass
2,AAA,2013J,30268,F,North Western Region,A Level or Equivalent,30-40%,35-55,0,60,Y,Withdrawn
3,AAA,2013J,31604,F,South East Region,A Level or Equivalent,50-60%,35-55,0,60,N,Pass
4,AAA,2013J,32885,F,West Midlands Region,Lower Than A Level,50-60%,0-35,0,60,N,Pass

================================================================================
TABLE: studentRegistration
================================================================================

Shape:
(32593, 5)

Columns:
['code_module', 'code_presentation', 'id_student', 'date_registration', 'date_unregistration']

Data types:
code_module                str
code_presentation          str
id_student               int64
date_registration      float64
date_unregistration    float64
dtype: object

Missing values:
date_unregistration    22521
date_registration         45
dtype: int64

First rows:

,code_module,code_presentation,id_student,date_registration,date_unregistration
0,AAA,2013J,11391,-159.0,NaN
1,AAA,2013J,28400,-53.0,NaN
2,AAA,2013J,30268,-92.0,12.0
3,AAA,2013J,31604,-52.0,NaN
4,AAA,2013J,32885,-176.0,NaN

================================================================================
TABLE: studentVle
================================================================================

Shape:
(10655280, 6)

Columns:
['code_module', 'code_presentation', 'id_student', 'id_site', 'date', 'sum_click']

Data types:
code_module            str
code_presentation      str
id_student           int64
id_site              int64
date                 int64
sum_click            int64
dtype: object

Missing values:
Series([], dtype: int64)

First rows:

  code_module code_presentation  id_student  id_site  date  sum_click
0         AAA             2013J       28400   546652   -10          4
1         AAA             2013J       28400   546652   -10          1
2         AAA             2013J       28400   546652   -10          1
3         AAA             2013J       28400   546614   -10         11
4         AAA             2013J       28400   546714   -10          1

================================================================================
TABLE: vle
================================================================================

Shape:
(6364, 6)

Columns:
['id_site', 'code_module', 'code_presentation', 'activity_type', 'week_from', 'week_to']

Data types:
id_site                int64
code_module              str
code_presentation        str
activity_type            str
week_from            float64
week_to              float64
dtype: object

Missing values:
week_from    5243
week_to      5243
dtype: int64

First rows:

   id_site code_module code_presentation activity_type  week_from  week_to
0   546943         AAA             2013J      resource        NaN      NaN
1   546712         AAA             2013J     oucontent        NaN      NaN
2   546998         AAA             2013J      resource        NaN      NaN
3   546888         AAA             2013J           url        NaN      NaN
4   547035         AAA             2013J      resource        NaN      NaN

In [10]:
main_keys = ["id_student", "code_module", "code_presentation"]

print("Main key columns:")
print(main_keys)

Main key columns:
['id_student', 'code_module', 'code_presentation']

In [11]:
student_info_total_rows = student_info.shape[0]
student_info_unique_keys = student_info[main_keys].drop_duplicates().shape[0]

print("student_info total rows:", student_info_total_rows)
print("student_info unique student-module-presentation keys:", student_info_unique_keys)
print("Is the main key unique in student_info?", student_info_total_rows == student_info_unique_keys)

student_info total rows: 32593
student_info unique student-module-presentation keys: 32593
Is the main key unique in student_info? True

In [12]:
student_registration_total_rows = student_registration.shape[0]
student_registration_unique_keys = student_registration[main_keys].drop_duplicates().shape[0]

print("student_registration total rows:", student_registration_total_rows)
print("student_registration unique student-module-presentation keys:", student_registration_unique_keys)
print("Is the main key unique in student_registration?", student_registration_total_rows == student_registration_unique_keys)

student_registration total rows: 32593
student_registration unique student-module-presentation keys: 32593
Is the main key unique in student_registration? True

In [13]:
student_info_keys = student_info[main_keys].drop_duplicates()
student_registration_keys = student_registration[main_keys].drop_duplicates()

merged_key_check = student_info_keys.merge(
    student_registration_keys,
    on=main_keys,
    how="outer",
    indicator=True
)

print("Key match status between student_info and student_registration:")
print(merged_key_check["_merge"].value_counts())

Key match status between student_info and student_registration:
_merge
both          32593
left_only         0
right_only        0
Name: count, dtype: int64

In [14]:
assessments_total_rows = assessments.shape[0]
assessments_unique_ids = assessments["id_assessment"].nunique()

print("assessments total rows:", assessments_total_rows)
print("unique id_assessment values:", assessments_unique_ids)
print("Is id_assessment unique in assessments?", assessments_total_rows == assessments_unique_ids)

assessments total rows: 206
unique id_assessment values: 206
Is id_assessment unique in assessments? True

In [15]:
student_assessment_ids = student_assessment["id_assessment"].drop_duplicates().to_frame()
assessment_ids = assessments[["id_assessment"]].drop_duplicates()

assessment_coverage_check = student_assessment_ids.merge(
    assessment_ids,
    on="id_assessment",
    how="left",
    indicator=True
)

print("Assessment coverage between student_assessment and assessments:")
print(assessment_coverage_check["_merge"].value_counts())

Assessment coverage between student_assessment and assessments:
_merge
both          188
left_only       0
right_only      0
Name: count, dtype: int64

In [16]:
student_vle_site_ids = student_vle["id_site"].drop_duplicates().to_frame()
vle_site_ids = vle[["id_site"]].drop_duplicates()

vle_coverage_check = student_vle_site_ids.merge(
    vle_site_ids,
    on="id_site",
    how="left",
    indicator=True
)

print("VLE site coverage between student_vle and vle:")
print(vle_coverage_check["_merge"].value_counts())

VLE site coverage between student_vle and vle:
_merge
both          6268
left_only        0
right_only       0
Name: count, dtype: int64

In [17]:
key_validation_summary = {
    "student_info_main_key_unique": student_info_total_rows == student_info_unique_keys,
    "student_registration_main_key_unique": student_registration_total_rows == student_registration_unique_keys,
    "assessment_id_unique": assessments_total_rows == assessments_unique_ids,
    "student_info_registration_key_match": merged_key_check["_merge"].value_counts().to_dict(),
    "student_assessment_coverage": assessment_coverage_check["_merge"].value_counts().to_dict(),
    "vle_site_coverage": vle_coverage_check["_merge"].value_counts().to_dict()
}

key_validation_summary

{'student_info_main_key_unique': True,
 'student_registration_main_key_unique': True,
 'assessment_id_unique': True,
 'student_info_registration_key_match': {'both': 32593,
  'left_only': 0,
  'right_only': 0},
 'student_assessment_coverage': {'both': 188, 'left_only': 0, 'right_only': 0},
 'vle_site_coverage': {'both': 6268, 'left_only': 0, 'right_only': 0}}

In [18]:
final_result_values = student_info["final_result"].value_counts()

print("final_result distribution:")
print(final_result_values)

final_result distribution:
final_result
Pass           12361
Withdrawn      10156
Fail            7052
Distinction     3024
Name: count, dtype: int64

In [19]:
student_base = student_info.copy()

print("student_base created successfully.")
print("Shape:", student_base.shape)

student_base created successfully.
Shape: (32593, 12)

In [20]:
risk_results = ["Withdrawn", "Fail"]
stable_results = ["Pass", "Distinction"]

student_base["at_risk_misalignment"] = np.where(
    student_base["final_result"].isin(risk_results),
    1,
    0
)

student_base[
    ["id_student", "code_module", "code_presentation", "final_result", "at_risk_misalignment"]
].head(10)

   id_student code_module code_presentation final_result  at_risk_misalignment
0       11391         AAA             2013J         Pass                     0
1       28400         AAA             2013J         Pass                     0
2       30268         AAA             2013J    Withdrawn                     1
3       31604         AAA             2013J         Pass                     0
4       32885         AAA             2013J         Pass                     0
5       38053         AAA             2013J         Pass                     0
6       45462         AAA             2013J         Pass                     0
7       45642         AAA             2013J         Pass                     0
8       52130         AAA             2013J         Pass                     0
9       53025         AAA             2013J         Pass                     0

In [21]:
target_mapping_check = pd.crosstab(
    student_base["final_result"],
    student_base["at_risk_misalignment"]
)

target_mapping_check

at_risk_misalignment      0      1
final_result
Distinction            3024      0
Fail                      0   7052
Pass                  12361      0
Withdrawn                 0  10156

In [22]:
target_counts = student_base["at_risk_misalignment"].value_counts()
target_percentages = student_base["at_risk_misalignment"].value_counts(normalize=True) * 100

target_summary = pd.DataFrame({
    "count": target_counts,
    "percentage": target_percentages.round(2)
})

target_summary

                      count  percentage
at_risk_misalignment
1                     17208        52.8
0                     15385        47.2

In [23]:
safe_registration_features = student_registration[
    main_keys + ["date_registration"]
].copy()

student_base = student_base.merge(
    safe_registration_features,
    on=main_keys,
    how="left"
)

print("student_base after adding safe registration features:")
print(student_base.shape)

student_base.head()

student_base after adding safe registration features:
(32593, 14)

,code_module,code_presentation,id_student,gender,region,highest_education,imd_band,age_band,num_of_prev_attempts,studied_credits,disability,final_result,at_risk_misalignment,date_registration
0,AAA,2013J,11391,M,East Anglian Region,HE Qualification,90-100%,55<=,0,240,N,Pass,0,-159.0
1,AAA,2013J,28400,F,Scotland,HE Qualification,20-30%,35-55,0,60,N,Pass,0,-53.0
2,AAA,2013J,30268,F,North Western Region,A Level or Equivalent,30-40%,35-55,0,60,Y,Withdrawn,1,-92.0
3,AAA,2013J,31604,F,South East Region,A Level or Equivalent,50-60%,35-55,0,60,N,Pass,0,-52.0
4,AAA,2013J,32885,F,West Midlands Region,Lower Than A Level,50-60%,0-35,0,60,N,Pass,0,-176.0

In [24]:
registration_missing = student_base["date_registration"].isnull().sum()

print("Missing date_registration values after merge:", registration_missing)
print("Total rows in student_base:", student_base.shape[0])

Missing date_registration values after merge: 45
Total rows in student_base: 32593

In [25]:
base_columns = [
    "id_student",
    "code_module",
    "code_presentation",
    "gender",
    "region",
    "highest_education",
    "imd_band",
    "age_band",
    "num_of_prev_attempts",
    "studied_credits",
    "disability",
    "date_registration",
    "final_result",
    "at_risk_misalignment"
]

base_student_dataset = student_base[base_columns].copy()

print("Initial base dataset created.")
print("Shape:", base_student_dataset.shape)

base_student_dataset.head()

Initial base dataset created.
Shape: (32593, 14)

,id_student,code_module,code_presentation,gender,region,highest_education,imd_band,age_band,num_of_prev_attempts,studied_credits,disability,date_registration,final_result,at_risk_misalignment
0,11391,AAA,2013J,M,East Anglian Region,HE Qualification,90-100%,55<=,0,240,N,-159.0,Pass,0
1,28400,AAA,2013J,F,Scotland,HE Qualification,20-30%,35-55,0,60,N,-53.0,Pass,0
2,30268,AAA,2013J,F,North Western Region,A Level or Equivalent,30-40%,35-55,0,60,Y,-92.0,Withdrawn,1
3,31604,AAA,2013J,F,South East Region,A Level or Equivalent,50-60%,35-55,0,60,N,-52.0,Pass,0
4,32885,AAA,2013J,F,West Midlands Region,Lower Than A Level,50-60%,0-35,0,60,N,-176.0,Pass,0

In [26]:
print("Shape:")
print(base_student_dataset.shape)

print("\nColumns:")
print(base_student_dataset.columns.tolist())

print("\nMissing values:")
print(base_student_dataset.isnull().sum().sort_values(ascending=False))

print("\nTarget distribution:")
print(base_student_dataset["at_risk_misalignment"].value_counts(normalize=True).round(4))

Shape:
(32593, 14)

Columns:
['id_student', 'code_module', 'code_presentation', 'gender', 'region', 'highest_education', 'imd_band', 'age_band', 'num_of_prev_attempts', 'studied_credits', 'disability', 'date_registration', 'final_result', 'at_risk_misalignment']

Missing values:
imd_band                1111
date_registration         45
code_presentation          0
gender                     0
id_student                 0
code_module                0
highest_education          0
region                     0
num_of_prev_attempts       0
age_band                   0
studied_credits            0
disability                 0
final_result               0
at_risk_misalignment       0
dtype: int64

Target distribution:
at_risk_misalignment
1    0.528
0    0.472
Name: proportion, dtype: float64

In [27]:
base_dataset_path = DATA_PROCESSED / "base_student_dataset.csv"

print("Base dataset output path:")
print(base_dataset_path)

Base dataset output path:
../data/processed/base_student_dataset.csv

In [28]:
base_student_dataset.to_csv(base_dataset_path, index=False)

print("Base student dataset saved successfully.")
print("Saved file:", base_dataset_path)
print("Shape:", base_student_dataset.shape)

Base student dataset saved successfully.
Saved file: ../data/processed/base_student_dataset.csv
Shape: (32593, 14)

In [29]:
base_student_dataset_check = pd.read_csv(base_dataset_path)

print("Reloaded dataset shape:")
print(base_student_dataset_check.shape)

print("\nReloaded dataset columns:")
print(base_student_dataset_check.columns.tolist())

print("\nFirst rows:")
display(base_student_dataset_check.head())

Reloaded dataset shape:
(32593, 14)

Reloaded dataset columns:
['id_student', 'code_module', 'code_presentation', 'gender', 'region', 'highest_education', 'imd_band', 'age_band', 'num_of_prev_attempts', 'studied_credits', 'disability', 'date_registration', 'final_result', 'at_risk_misalignment']

First rows:

,id_student,code_module,code_presentation,gender,region,highest_education,imd_band,age_band,num_of_prev_attempts,studied_credits,disability,date_registration,final_result,at_risk_misalignment
0,11391,AAA,2013J,M,East Anglian Region,HE Qualification,90-100%,55<=,0,240,N,-159.0,Pass,0
1,28400,AAA,2013J,F,Scotland,HE Qualification,20-30%,35-55,0,60,N,-53.0,Pass,0
2,30268,AAA,2013J,F,North Western Region,A Level or Equivalent,30-40%,35-55,0,60,Y,-92.0,Withdrawn,1
3,31604,AAA,2013J,F,South East Region,A Level or Equivalent,50-60%,35-55,0,60,N,-52.0,Pass,0
4,32885,AAA,2013J,F,West Midlands Region,Lower Than A Level,50-60%,0-35,0,60,N,-176.0,Pass,0

Notebook 01 Summary

This notebook completed the initial data loading and validation stage.

Completed steps:

1. Loaded all seven OULAD CSV files.
2. Inspected table shapes, columns, data types, missing values, and first rows.
3. Validated the main student-module-presentation key.
4. Confirmed that `studentInfo` can be used as the base student-level table.
5. Created the target variable `at_risk_misalignment`.
6. Added safe registration information using `date_registration`.
7. Excluded `date_unregistration` to avoid data leakage.
8. Saved the first processed base dataset.

Saved output:

`data/processed/base_student_dataset.csv`

Next notebook:

`02_early_behavior_features.ipynb`

The next notebook will create early behavioral features from VLE interactions and assessment submissions.